network:
    ethernets:
        enp5s0:
            dhcp4: false
            dhcp6: false
            link-local: []
            addresses: [10.0.110.0/8]
            gateway4: 10.0.0.1
            nameservers:
                addresses: [10.0.0.1, 8.8.8.8]
        enp9s0:
            dhcp4: false
            dhcp6: false
            link-local: []
            addresses: [172.29.0.1/16]
    version: 2
