version: '3'
services:
  jira:
    image: atlassian/jira-software:latest
    container_name: jira
    networks:
      - jiranet
    volumes: 
      - jira_home:/var/atlassian/application-data/jira
    ports: 
      - 8080:8080
    environment:
      - JVM_MINIMUM_MEMORY=512m
      - JVM_MAXIMUM_MEMORY=2048m
      - ATL_TOMCAT_PORT=8080
      - ATL_TOMCAT_CONTEXTPATH=
      - ATL_PROXY_NAME=jira.sdte.dev
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_SCHEME=https
      - ATL_TOMCAT_SECURE=true
volumes:
  jira_home:
    external: true

networks:
  jiranet:
    external: true

