apiVersion: v1
kind: Service
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  ports:
  - name: ssh
    port: 22
    targetPort: 22
  selector:
    app: ubuntu
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  namespace: default
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        ports:
        - name: ssh
          containerPort: 22
